kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: pod-test-1
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: example-web
  mode: all
  action: pod-failure
  duration: 5m
